---
abstract: 'write a heap dump file for later analysis'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  ExtUtils::CBuilder: '0'
  Test::More: '0.88'
configure_requires:
  Module::Build: '0.4004'
dynamic_config: 1
generated_by: 'Module::Build version 0.4224, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Devel-MAT-Dumper
provides:
  Devel::MAT::Dumper:
    file: lib/Devel/MAT/Dumper.pm
    version: '0.42'
  Devel::MAT::Dumper::Helper:
    file: lib/Devel/MAT/Dumper/Helper.pm
    version: '0.42'
requires:
  File::Spec: '0'
  perl: '5.010'
resources:
  license: http://dev.perl.org/licenses/
version: '0.42'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
